services:
  backend:
    command: >
      sh -c "
            cd myproject &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    
    volumes:
      - ./backend:/app/myproject